### ISSUE TITLE
Matrix-free operations

### ISSUE THREAD

**Issue by panpat** [kul-forbes/ForBES#7]
I am trying to solve a problem with a standard least-squares cost where the matrix A is not explicitly available. I thought it was possible to do that using linop but when I try to run the code I get an error:

Undefined operator '*' for input arguments of type 'struct'.

Error in ProblemComposite/EstimateLipschitz>@(x)vec(prob.C1'*(prob.Q(prob.C1*reshape(x,prob.n)))) (line 15)
    funHessian = @(x) vec(prob.C1'*(prob.Q(prob.C1*reshape(x, prob.n))));

It seems that there is no possibility of using a linear operator instead of a full matrix in aff? 
How can this be fixed?

**Comment by lostella** [comment]
From what I understand by searching `makeop` and `makeadj` in the code, it looks like `linOp` (as well as `diagOp`, `sumOp`, `stackOp`, `matOp`, `hankelOp`) is outdated code that was just left there and will just not work with the algorithms: they should probably just be removed. I probably abandoned them in favor of using stuff from Spot. So one immediate solution is using this structure, by providing it the direct and adjoint maps: http://www.cs.ubc.ca/labs/scl/spot/operators.html#opFunction

Let me know if that works!

**Comment by panpat** [comment]
I modeled it as a quadratic function instead, which seems to accept operators as Hessians. It seems to work now.

**Comment by lostella** [comment]
Sure, but in case you want to properly pass it as a separate object, try the above solution, it would be nice if that worked (I don't see why it shouldn't).

**Comment by panpat** [comment]
If I use this then I need to modify many parts of the code where there is prob.C1*something and prob.C1'*something. Not time for this...

**Comment by lostella** [comment]
No, you shouldn't need to modify anything: the operators in Spot are structures that have `*` as well as `'` defined over them, so they work just as if they were matrices. You just need to pass the right function (or cell-array of functions) when constructing it, see: http://www.cs.ubc.ca/labs/scl/spot/operators.html#opFunction, and you they will work with `C1*x` and `C1'*x`
